// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lyra_config.proto

#include "lyra_config.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace third_party {
namespace lyra_codec {
PROTOBUF_CONSTEXPR LyraConfig::LyraConfig(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.identifier_)*/0} {}
struct LyraConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LyraConfigDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~LyraConfigDefaultTypeInternal() {}
  union {
    LyraConfig _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LyraConfigDefaultTypeInternal _LyraConfig_default_instance_;
}  // namespace lyra_codec
}  // namespace third_party
static ::_pb::Metadata file_level_metadata_lyra_5fconfig_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_lyra_5fconfig_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_lyra_5fconfig_2eproto = nullptr;

const uint32_t TableStruct_lyra_5fconfig_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::third_party::lyra_codec::LyraConfig, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::third_party::lyra_codec::LyraConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::third_party::lyra_codec::LyraConfig, _impl_.identifier_),
  0,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, -1, sizeof(::third_party::lyra_codec::LyraConfig)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::third_party::lyra_codec::_LyraConfig_default_instance_._instance,
};

const char descriptor_table_protodef_lyra_5fconfig_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021lyra_config.proto\022\026third_party.lyra_co"
  "dec\" \n\nLyraConfig\022\022\n\nidentifier\030\001 \001(\005"
  ;
static ::_pbi::once_flag descriptor_table_lyra_5fconfig_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_lyra_5fconfig_2eproto = {
    false, false, 77, descriptor_table_protodef_lyra_5fconfig_2eproto,
    "lyra_config.proto",
    &descriptor_table_lyra_5fconfig_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_lyra_5fconfig_2eproto::offsets,
    file_level_metadata_lyra_5fconfig_2eproto, file_level_enum_descriptors_lyra_5fconfig_2eproto,
    file_level_service_descriptors_lyra_5fconfig_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_lyra_5fconfig_2eproto_getter() {
  return &descriptor_table_lyra_5fconfig_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_lyra_5fconfig_2eproto(&descriptor_table_lyra_5fconfig_2eproto);
namespace third_party {
namespace lyra_codec {

// ===================================================================

class LyraConfig::_Internal {
 public:
  using HasBits = decltype(std::declval<LyraConfig>()._impl_._has_bits_);
  static void set_has_identifier(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

LyraConfig::LyraConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:third_party.lyra_codec.LyraConfig)
}
LyraConfig::LyraConfig(const LyraConfig& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  LyraConfig* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.identifier_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.identifier_ = from._impl_.identifier_;
  // @@protoc_insertion_point(copy_constructor:third_party.lyra_codec.LyraConfig)
}

inline void LyraConfig::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.identifier_){0}
  };
}

LyraConfig::~LyraConfig() {
  // @@protoc_insertion_point(destructor:third_party.lyra_codec.LyraConfig)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void LyraConfig::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void LyraConfig::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void LyraConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:third_party.lyra_codec.LyraConfig)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.identifier_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LyraConfig::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional int32 identifier = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_identifier(&has_bits);
          _impl_.identifier_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* LyraConfig::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:third_party.lyra_codec.LyraConfig)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional int32 identifier = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_identifier(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:third_party.lyra_codec.LyraConfig)
  return target;
}

size_t LyraConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:third_party.lyra_codec.LyraConfig)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional int32 identifier = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_identifier());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData LyraConfig::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    LyraConfig::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*LyraConfig::GetClassData() const { return &_class_data_; }


void LyraConfig::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<LyraConfig*>(&to_msg);
  auto& from = static_cast<const LyraConfig&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:third_party.lyra_codec.LyraConfig)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_identifier()) {
    _this->_internal_set_identifier(from._internal_identifier());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void LyraConfig::CopyFrom(const LyraConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:third_party.lyra_codec.LyraConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LyraConfig::IsInitialized() const {
  return true;
}

void LyraConfig::InternalSwap(LyraConfig* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.identifier_, other->_impl_.identifier_);
}

::PROTOBUF_NAMESPACE_ID::Metadata LyraConfig::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_lyra_5fconfig_2eproto_getter, &descriptor_table_lyra_5fconfig_2eproto_once,
      file_level_metadata_lyra_5fconfig_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace lyra_codec
}  // namespace third_party
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::third_party::lyra_codec::LyraConfig*
Arena::CreateMaybeMessage< ::third_party::lyra_codec::LyraConfig >(Arena* arena) {
  return Arena::CreateMessageInternal< ::third_party::lyra_codec::LyraConfig >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
