// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lyra_config.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_lyra_5fconfig_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_lyra_5fconfig_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_lyra_5fconfig_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_lyra_5fconfig_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_lyra_5fconfig_2eproto;
namespace third_party {
namespace lyra_codec {
class LyraConfig;
struct LyraConfigDefaultTypeInternal;
extern LyraConfigDefaultTypeInternal _LyraConfig_default_instance_;
}  // namespace lyra_codec
}  // namespace third_party
PROTOBUF_NAMESPACE_OPEN
template<> ::third_party::lyra_codec::LyraConfig* Arena::CreateMaybeMessage<::third_party::lyra_codec::LyraConfig>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace third_party {
namespace lyra_codec {

// ===================================================================

class LyraConfig final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:third_party.lyra_codec.LyraConfig) */ {
 public:
  inline LyraConfig() : LyraConfig(nullptr) {}
  ~LyraConfig() override;
  explicit PROTOBUF_CONSTEXPR LyraConfig(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LyraConfig(const LyraConfig& from);
  LyraConfig(LyraConfig&& from) noexcept
    : LyraConfig() {
    *this = ::std::move(from);
  }

  inline LyraConfig& operator=(const LyraConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline LyraConfig& operator=(LyraConfig&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LyraConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const LyraConfig* internal_default_instance() {
    return reinterpret_cast<const LyraConfig*>(
               &_LyraConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LyraConfig& a, LyraConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(LyraConfig* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LyraConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LyraConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LyraConfig>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LyraConfig& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LyraConfig& from) {
    LyraConfig::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LyraConfig* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "third_party.lyra_codec.LyraConfig";
  }
  protected:
  explicit LyraConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdentifierFieldNumber = 1,
  };
  // optional int32 identifier = 1;
  bool has_identifier() const;
  private:
  bool _internal_has_identifier() const;
  public:
  void clear_identifier();
  int32_t identifier() const;
  void set_identifier(int32_t value);
  private:
  int32_t _internal_identifier() const;
  void _internal_set_identifier(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:third_party.lyra_codec.LyraConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    int32_t identifier_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_lyra_5fconfig_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LyraConfig

// optional int32 identifier = 1;
inline bool LyraConfig::_internal_has_identifier() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool LyraConfig::has_identifier() const {
  return _internal_has_identifier();
}
inline void LyraConfig::clear_identifier() {
  _impl_.identifier_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline int32_t LyraConfig::_internal_identifier() const {
  return _impl_.identifier_;
}
inline int32_t LyraConfig::identifier() const {
  // @@protoc_insertion_point(field_get:third_party.lyra_codec.LyraConfig.identifier)
  return _internal_identifier();
}
inline void LyraConfig::_internal_set_identifier(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.identifier_ = value;
}
inline void LyraConfig::set_identifier(int32_t value) {
  _internal_set_identifier(value);
  // @@protoc_insertion_point(field_set:third_party.lyra_codec.LyraConfig.identifier)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace lyra_codec
}  // namespace third_party

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_lyra_5fconfig_2eproto
